# taken from: https://packaging.python.org/guides/supporting-windows-using-appveyor/
environment:

  global:
      MINGW: C:\tools\mingw64\bin\
      PATH: C:\tools\mingw64\bin;$(PATH)

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # also need mingw for fortran I think
  - "cinst mingw"
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install pip -U"
  - "%PYTHON%\\python.exe -m pip install wheel numpy"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "echo No tests to run"

after_test:
  # This step builds your wheels.
  # Again, you only need build.cmd if you're building C extensions for
  # 64-bit Python 3.3/3.4. And you need to use %PYTHON% to get the correct
  # interpreter
  - "%PYTHON%\\python.exe setup.py build_ext --compiler mingw64 --fcompiler gfortran "
  - "%PYTHON%\\python.exe -m pip wheel ."

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
