name: build

on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
    paths:
      - .github/workflows/build.yml

jobs:
    sdist:
        name: sdist
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true

            - name: Build sdist
              run: pipx run build --sdist

            - uses: actions/upload-artifact@v4
              with:
                name: sdist
                path: dist/*.tar.gz

    build_wheels:
        name: build_wheels for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-13, macos-14]

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true

            - name: Provide gfortran (macOS)
              if: runner.os == 'macOS'
              run: |
                ARCH=$(uname -m)
                if [ "$ARCH" == "arm64" ]; then
                    sudo ln -fs /opt/homebrew/bin/gfortran-12 /opt/homebrew/bin/gfortran
                else
                    sudo ln -fs /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
                fi

                gfortran --version

            - name: Provide gfortran (Windows)
              if: runner.os == 'Windows'
              uses: msys2/setup-msys2@v2
              with:
                path-type: inherit
                msystem: mingw64
                install: |
                  mingw-w64-x86_64-gcc-fortran

            - name: Build wheels with cibuildwheel on Linux
              if: matrix.os == 'ubuntu-latest'
              run: pipx run cibuildwheel

            - name: Build wheels with cibuildwheel on Windows
              if: matrix.os == 'windows-latest'
              shell: msys2 {0}
              run: pipx run cibuildwheel
              env:
                CIBW_ENVIRONMENT_WINDOWS: CC=gcc CXX=g++ FC=gfortran CMAKE_ARGS='-G "MSYS Makefiles"'

            - name: Build wheels with cibuildwheel on MacOS 13
              if: matrix.os == 'macos-13'
              run: pipx run cibuildwheel
              env:
                CIBW_REPAIR_WHEEL_COMMAND: "delocate-wheel --require-archs {delocate_archs} --require-target-macos-version 13.0 -w {dest_dir} -v {wheel} "

            - name: Build wheels with cibuildwheel on MacOS 14
              if: matrix.os == 'macos-14'
              run: pipx run cibuildwheel
              env:
                CIBW_REPAIR_WHEEL_COMMAND: "delocate-wheel --require-archs {delocate_archs} --require-target-macos-version 14.0 -w {dest_dir} -v {wheel} "

            - uses: actions/upload-artifact@v4
              with:
                name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: wheelhouse/*.whl
