name: build

on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
    paths:
      - .github/workflows/build.yml

jobs:
    sdist:
        name: sdist
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true

            - name: Build sdist
              run: pipx run build --sdist

            - uses: actions/upload-artifact@v4
              with:
                name: sdist
                path: dist/*.tar.gz

    build_wheels:
        name: build_wheels for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-13, macos-14]

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true

            - name: Provide gfortran (macOS)
              if: runner.os == 'macOS'
              run: |
                ARCH=$(uname -m)
                if [ "$ARCH" == "arm64" ]; then
                    sudo ln -fs /opt/homebrew/bin/gfortran-12 /opt/homebrew/bin/gfortran
                else
                    sudo ln -fs /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
                fi

                gfortran --version

            - name: Provide gfortran (Windows)
              if: runner.os == 'Windows'
              uses: msys2/setup-msys2@v2

            - name: Build wheels with cibuildwheel
              run: pipx run cibuildwheel

            - uses: actions/upload-artifact@v4
              with:
                name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: wheelhouse/*.whl
