name: build

on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
    paths:
      - .github/workflows/build.yml

jobs:
    sdist:
        name: sdist
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Optional, use if you use setuptools_scm
                submodules: true # Optional, use if you have submodules

            - name: Build sdist
              run: pipx run build --sdist

            - uses: actions/upload-artifact@v4
              with:
                name: sdist
                path: dist/*.tar.gz

    build_wheels:
        name: build_wheels for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-13, macos-14]

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true

            - uses: pypa/cibuildwheel@v2.19.1
              with:
                config-file: "./pyproject.toml"

            - uses: actions/upload-artifact@v4
              with:
                name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: wheelhouse/*.whl
